/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion.cliente2;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author cvelez
 */
public class VistaSimulacion2 extends javax.swing.JDialog {

    private final Modelo2 modelo2;
    private ControladorSimulacion2 controller;
    /**
     * Creates new form VistaSimulacion
     */
    public VistaSimulacion2(Modelo2 thisModelo) {
        modelo2 = thisModelo;
        initComponents();
        asignarListener();
 
    }
    
    public ControladorSimulacion2 getControlador() {
        if(controller == null){
            controller = new ControladorSimulacion2(this);
        }
        return controller;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        btnGroupVehicular = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_numConjunto = new javax.swing.JLabel();
        btnRojo = new javax.swing.JRadioButton();
        btnAmarillo = new javax.swing.JRadioButton();
        btnVerde = new javax.swing.JRadioButton();
        lbl_img1 = new javax.swing.JLabel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_img3 = new javax.swing.JLabel();
        lbl_img11 = new javax.swing.JLabel();
        lbl_img22 = new javax.swing.JLabel();
        lbl_img33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_numConjunto1 = new javax.swing.JLabel();
        lbl_grup2_image_red = new javax.swing.JLabel();
        lbl_grup2_image_yellow = new javax.swing.JLabel();
        lbl_grup2_image_green = new javax.swing.JLabel();
        lbl_grup2_image_red_2 = new javax.swing.JLabel();
        lbl_grup2_image_green_2 = new javax.swing.JLabel();
        btnRojo_grup2 = new javax.swing.JRadioButton();
        btnAmarillo_grup2 = new javax.swing.JRadioButton();
        btnVerde_grup2 = new javax.swing.JRadioButton();
        lbl_grup2_image_yellow1 = new javax.swing.JLabel();
        btn_off = new javax.swing.JButton();
        btn_on = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Simulación tarjeta semafórica N° 2");

        lbl_numConjunto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_numConjunto.setText("Grupo 1");

        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnAmarillo.setText("Amarillo");

        btnVerde.setText("Verde");

        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red_false.png"))); // NOI18N

        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yellow_false.png"))); // NOI18N

        lbl_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/green_false.png"))); // NOI18N

        lbl_img11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red_false.png"))); // NOI18N

        lbl_img22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yellow_false.png"))); // NOI18N

        lbl_img33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/green_false.png"))); // NOI18N

        lbl_numConjunto1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_numConjunto1.setText("Grupo 2");

        lbl_grup2_image_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red_false.png"))); // NOI18N

        lbl_grup2_image_yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yellow_false.png"))); // NOI18N

        lbl_grup2_image_green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/green_false.png"))); // NOI18N

        lbl_grup2_image_red_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red_false.png"))); // NOI18N

        lbl_grup2_image_green_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/green_false.png"))); // NOI18N

        btnRojo_grup2.setText("Rojo");
        btnRojo_grup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojo_grup2ActionPerformed(evt);
            }
        });

        btnAmarillo_grup2.setText("Amarillo");

        btnVerde_grup2.setText("Verde");

        lbl_grup2_image_yellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yellow_false.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_numConjunto1)
                    .addComponent(btnVerde_grup2)
                    .addComponent(btnAmarillo_grup2)
                    .addComponent(btnRojo_grup2))
                .addGap(216, 216, 216)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_grup2_image_yellow)
                    .addComponent(lbl_grup2_image_red)
                    .addComponent(lbl_grup2_image_green, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_grup2_image_red_2)
                    .addComponent(lbl_grup2_image_green_2)
                    .addComponent(lbl_grup2_image_yellow1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_numConjunto1)
                .addGap(8, 8, 8)
                .addComponent(btnRojo_grup2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAmarillo_grup2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerde_grup2)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_grup2_image_red_2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_grup2_image_yellow1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_grup2_image_red, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_grup2_image_yellow)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_grup2_image_green)
                    .addComponent(lbl_grup2_image_green_2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_img1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_img11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_img2)
                                    .addComponent(lbl_img3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_img22)
                                    .addComponent(lbl_img33))))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRojo)
                            .addComponent(btnAmarillo)
                            .addComponent(btnVerde)))
                    .addComponent(lbl_numConjunto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_numConjunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_img22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_img33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_img11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_img2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_img3)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAmarillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerde)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_off.setText("Apagar todo");

        btn_on.setText("Encender todo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_on)
                    .addComponent(btn_off, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_off)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_on)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed

    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnRojo_grup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojo_grup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRojo_grup2ActionPerformed

    
    private void asignarListener() {
        btnRojo.addActionListener(getControlador());
        btnAmarillo.addActionListener(getControlador());
        btnVerde.addActionListener(getControlador());
        btnRojo_grup2.addActionListener(getControlador());
        btnAmarillo_grup2.addActionListener(getControlador());
        btnVerde_grup2.addActionListener(getControlador());
        btn_off.addActionListener(getControlador());
        btn_on.addActionListener(getControlador());
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.JRadioButton btnAmarillo_grup2;
    private javax.swing.ButtonGroup btnGroupVehicular;
    private javax.swing.JRadioButton btnRojo;
    private javax.swing.JRadioButton btnRojo_grup2;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.JRadioButton btnVerde_grup2;
    private javax.swing.JButton btn_off;
    private javax.swing.JButton btn_on;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_grup2_image_green;
    private javax.swing.JLabel lbl_grup2_image_green_2;
    private javax.swing.JLabel lbl_grup2_image_red;
    private javax.swing.JLabel lbl_grup2_image_red_2;
    private javax.swing.JLabel lbl_grup2_image_yellow;
    private javax.swing.JLabel lbl_grup2_image_yellow1;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lbl_img11;
    private javax.swing.JLabel lbl_img2;
    private javax.swing.JLabel lbl_img22;
    private javax.swing.JLabel lbl_img3;
    private javax.swing.JLabel lbl_img33;
    private javax.swing.JLabel lbl_numConjunto;
    private javax.swing.JLabel lbl_numConjunto1;
    // End of variables declaration//GEN-END:variables
    
    
    public ButtonGroup getBtnGroupVehicular() {
        return btnGroupVehicular;
    }
    
    public JRadioButton getBtnRojo() {
        return btnRojo;
    }

    public JRadioButton getBtnAmarillo() {
        return btnAmarillo;
    }

    public JRadioButton getBtnVerde() {
        return btnVerde;
    }
    
    public Modelo2 getModelo() {
        return modelo2;
    }

    public JLabel getLbl_img1() {
        return lbl_img1;
    }
    
    public JLabel getLbl_img11() {
        return lbl_img11;
    }
    public JLabel getLbl_img2() {
        return lbl_img2;
    }
    public JLabel getLbl_img22() {
        return lbl_img22;
    }
    public JLabel getLbl_img3() {
        return lbl_img3;
    }
        public JLabel getLbl_img33() {
        return lbl_img33;
    }

    public JRadioButton getBtnAmarillo_grup2() {
        return btnAmarillo_grup2;
    }

    public JRadioButton getBtnRojo_grup2() {
        return btnRojo_grup2;
    }

    public JRadioButton getBtnVerde_grup2() {
        return btnVerde_grup2;
    }

    public JLabel getLbl_grup2_image_green() {
        return lbl_grup2_image_green;
    }

    public JLabel getLbl_grup2_image_green_2() {
        return lbl_grup2_image_green_2;
    }

    public JLabel getLbl_grup2_image_red() {
        return lbl_grup2_image_red;
    }
    


    public JLabel getLbl_grup2_image_red_2() {
        return lbl_grup2_image_red_2;
    }

    public JLabel getLbl_grup2_image_yellow() {
        return lbl_grup2_image_yellow;
    }
    public JLabel getLbl_grup2_image_yellow1() {
        return lbl_grup2_image_yellow1;
    }


    public JButton getBtn_off() {
        return btn_off;
    }

    public JButton getBtn_on() {
        return btn_on;
    }





    
}
